import { TOOL_COLORS } from '@/constants/designTokens'

export const TOOL_CONFIG = {
  camel: {
    label: 'CAMeL Tools',
    color: TOOL_COLORS.camel.border,
    group: TOOL_COLORS.camel.group,
    type: 'Hybrid Rule + Neural',
    license: 'MIT',
    features: ['Lemma', 'Root', 'POS', 'Morphology', 'Gloss'],
    paper: 'Obeid et al. 2020, ACL',
    provides: ['lemma', 'root', 'pos', 'gender', 'number', 'tense', 'gloss'],
  },
  farasa: {
    label: 'Farasa',
    color: TOOL_COLORS.farasa.border,
    group: TOOL_COLORS.farasa.group,
    type: 'Statistical (SVM-rank)',
    license: 'Free (research)',
    features: ['Segmentation', 'Diacritization'],
    paper: 'Abdelali et al. 2016, NAACL',
    provides: ['segmentation'],
  },
  stanza: {
    label: 'Stanza',
    color: TOOL_COLORS.stanza.border,
    group: TOOL_COLORS.stanza.group,
    type: 'Neural (BiLSTM)',
    license: 'Apache 2.0',
    features: ['POS', 'Lemma', 'Dependency', 'Case'],
    paper: 'Qi et al. 2020, ACL',
    provides: ['lemma', 'pos', 'case', 'definite', 'dependency'],
  },
  qalsadi: {
    label: 'Qalsadi',
    color: TOOL_COLORS.qalsadi.border,
    group: TOOL_COLORS.qalsadi.group,
    type: 'Rule-based morphological',
    license: 'LGPL',
    features: ['Lemma', 'Stem'],
    paper: 'Zerrouki 2017',
    provides: ['lemma', 'stem'],
  },
  arabert: {
    label: 'AraBERT',
    color: TOOL_COLORS.camel.border,
    group: TOOL_COLORS.camel.group,
    type: 'Neural (BERT)',
    license: 'Apache 2.0',
    features: ['POS', 'NER', 'Contextual embeddings'],
    paper: 'Antoun et al. 2020, LREC',
    provides: ['lemma', 'pos'],
  },
  alkhalil: {
    label: 'AlKhalil',
    color: TOOL_COLORS.alkhalil.border,
    group: TOOL_COLORS.alkhalil.group,
    type: 'Rule-based',
    license: 'Free (research)',
    features: ['Root extraction', 'Full morphology'],
    paper: 'Boudchiche et al. 2017',
    provides: ['lemma', 'root', 'pos'],
  },
  udpipe: {
    label: 'UDPipe 2',
    color: TOOL_COLORS.udpipe.border,
    group: TOOL_COLORS.udpipe.group,
    type: 'Neural (transition-based)',
    license: 'MPL 2.0',
    features: ['POS', 'Dependency parsing', 'Lemma'],
    paper: 'Straka 2018, CoNLL',
    provides: ['lemma', 'pos', 'dependency'],
  },
  madamira: {
    label: 'MADAMIRA',
    color: TOOL_COLORS.farasa.border,
    group: TOOL_COLORS.farasa.group,
    type: 'Statistical + Rule-based',
    license: 'LDC (research)',
    features: ['Full morphology', 'Diacritization', 'POS'],
    paper: 'Pasha et al. 2014, LREC',
    provides: ['lemma', 'pos', 'gender', 'number'],
  },
  sinatools: {
    label: 'SinaTools / Alma',
    color: TOOL_COLORS.farasa.border,
    group: TOOL_COLORS.farasa.group,
    type: 'Frequency + BERT',
    license: 'MIT',
    features: ['Lemmatization', 'POS tagging', 'NER', 'Word Sense Disambiguation'],
    paper: 'Jarrar et al. 2022, Birzeit University',
    provides: ['lemma', 'pos'],
  },
}

export const TOOL_KEYS = Object.keys(TOOL_CONFIG)

export function toolOrder(keys = TOOL_KEYS) {
  return keys.filter((key) => TOOL_CONFIG[key])
}
